"""Emit the human/AI-readable map (MAP.md) and the project-root pointer.

MAP.md is intentionally bounded (top-N symbols per file) so it stays scannable —
the full detail lives in the queryable index. Files are written with Obsidian
`[[wikilinks]]` so the same tree opens as an interactive graph in Obsidian.
"""

from __future__ import annotations

import time
from collections import defaultdict

from . import CLI_NAME, DATA_DIR, MAP_FILE, POINTER_FILE, TOOL_NAME, __version__
from .config import Config
from .graph import Graph
from .model import CONTAINS, DEFINES, FILE, MODULE


def _files(graph: Graph):
    return [n for n in graph.nodes.values() if n.kind in (FILE, MODULE) and n.path]


def _children(graph: Graph):
    kids = defaultdict(list)
    for e in graph.edges:
        if e.kind in (DEFINES, CONTAINS):
            src = graph.nodes.get(e.src)
            dst = graph.nodes.get(e.dst)
            if src and dst and src.kind in (FILE, MODULE):
                kids[e.src].append(dst)
    return kids


def write_map(cfg: Config, graph: Graph) -> str:
    files = _files(graph)
    kids = _children(graph)
    stats = graph.stats()

    lines: list[str] = []
    lines.append(f"# {TOOL_NAME} map — {cfg.root.name}")
    lines.append("")
    lines.append(f"> Auto-generated by {TOOL_NAME} v{__version__}. Do not hand-edit; "
                 f"run `{CLI_NAME} sync`.")
    lines.append(f"> Generated {time.strftime('%Y-%m-%d %H:%M:%S')}.")
    lines.append("")
    lines.append("**For AI agents:** before reading source files to understand this "
                 "project, look things up here first:")
    lines.append(f"- `{CLI_NAME} query <term>` — find a file/symbol/heading by name or summary")
    lines.append(f"- `{CLI_NAME} context <symbol>` — a symbol's definition, callers, callees, siblings")
    lines.append(f"- `{CLI_NAME} importers <path>` — what depends on a file")
    lines.append(f"- `{CLI_NAME} hubs` — the most central files")
    lines.append("")

    lines.append("## Overview")
    lines.append("")
    lines.append(f"- Nodes: **{stats['nodes']}** · Edges: **{stats['edges']}**")
    nk = stats["node_kinds"]
    lines.append("- Node kinds: " + ", ".join(f"{k} {v}" for k, v in nk.items()))
    ek = stats["edge_kinds"]
    if ek:
        lines.append("- Edge kinds: " + ", ".join(f"{k} {v}" for k, v in ek.items()))
    lines.append("")

    hub_files = sorted(files, key=lambda n: n.rank, reverse=True)[:15]
    if hub_files:
        lines.append("## Hub files (most depended-upon)")
        lines.append("")
        for n in hub_files:
            summ = f" — {n.summary}" if n.summary else ""
            lines.append(f"1. [[{n.path}]] · `{n.lang}` · {n.loc} LOC · rank {n.rank}{summ}")
        lines.append("")

    lines.append("## Project tree")
    lines.append("")
    by_dir = defaultdict(list)
    for n in files:
        d = n.path.rsplit("/", 1)[0] if "/" in n.path else "."
        by_dir[d].append(n)

    for d in sorted(by_dir):
        lines.append(f"### `{d}/`" if d != "." else "### `<root>`")
        lines.append("")
        for n in sorted(by_dir[d], key=lambda x: x.path)[: cfg.max_map_files_per_dir]:
            summ = f" — {n.summary}" if n.summary else ""
            lines.append(f"- [[{n.path}]] · {n.loc} LOC{summ}")
            syms = sorted(kids.get(n.id, []), key=lambda x: x.line)
            shown = syms[: cfg.max_symbols_per_file_in_map]
            for s in shown:
                s_summ = f" — {s.summary}" if s.summary else ""
                lines.append(f"    - `{s.kind}` **{s.name}** :{s.line}{s_summ}")
            if len(syms) > len(shown):
                more = len(syms) - len(shown)
                lines.append(f"    - …{more} more (`{CLI_NAME} query` inside {n.path})")
        lines.append("")

    from .secure import harden_file, secure_dir
    secure_dir(cfg.data_dir)
    out = cfg.data_dir / MAP_FILE
    out.write_text("\n".join(lines), "utf-8")
    harden_file(out)
    return str(out)


def write_pointer(cfg: Config) -> str:
    """Drop a small, visible pointer at the project root for any agent to find."""
    text = f"""\
# {TOOL_NAME}

This project is mapped by **{TOOL_NAME}** — a self-updating knowledge graph that
lets AI agents look things up instead of re-reading the whole tree.

**Agents: read this before exploring.**

1. The map lives in `{DATA_DIR}/{MAP_FILE}` (Markdown, always safe to read).
2. Prefer lookups over full-file reads to save context/tokens:
   - `{CLI_NAME} query <term>` — locate a file/symbol/heading
   - `{CLI_NAME} context <symbol>` — definition + callers + callees
   - `{CLI_NAME} importers <path>` — reverse dependencies
   - `{CLI_NAME} hubs` — the most central files
3. After you create or edit files, refresh the map: `{CLI_NAME} sync`
   (this is automatic if the {TOOL_NAME} PostToolUse hook is installed).

If the `{CLI_NAME}` command is unavailable, run `python3 -m cortex <args>` from the
{TOOL_NAME} install, or just read `{DATA_DIR}/{MAP_FILE}` directly.
"""
    out = cfg.root / POINTER_FILE
    out.write_text(text, "utf-8")
    return str(out)
